In [5]:
import pandas as pd
df = pd.read_csv("train1.csv")
df


id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 5 columns]

In [6]:
df['text'][100]

'By Patrick Wood By its very nature, the Internet Corporation for Assigned Names and Numbers (ICANN) is a non-profit organization exclusively run by Technocrats. As... '

In [7]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [8]:
df.shape

(20800, 5)

In [9]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [10]:
df = df.dropna()
df=df.reset_index(drop=True)

In [11]:
df.head(20)

id                                              title  \
0    0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1    1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2    2                  Why the Truth Might Get You Fired   
3    3  15 Civilians Killed In Single US Airstrike Hav...   
4    4  Iranian woman jailed for fictional unpublished...   
5    5  Jackie Mason: Hollywood Would Love Trump if He...   
6    7  Benoît Hamon Wins French Socialist Party’s Pre...   
7    9  A Back-Channel Plan for Ukraine and Russia, Co...   
8   10  Obama’s Organizing for Action Partners with So...   
9   11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   
10  12  Russian Researchers Discover Secret Nazi Milit...   
11  13  US Officials See No Link Between Trump and Russia   
12  14  Re: Yes, There Are Paid Government Trolls On S...   
13  15  In Major League Soccer, Argentines Find a Home...   
14  16  Wells Fargo Chief Abruptly Steps Down - The Ne...   
15  17  Anonymous Donor Pays $2.5 Million To Release E...   
16  18                          FBI Closes In On Hillary!   
17  19  Chuck Todd: ’BuzzFeed Did Donald Trump a Polit...   
18  21  Monica Lewinsky, Clinton Sex Scandal Set for ’...   
19  22  Rob Reiner: Trump Is ’Mentally Unstable’ - Bre...   

                              author  \
0                      Darrell Lucus   
1                    Daniel J. Flynn   
2                 Consortiumnews.com   
3                    Jessica Purkiss   
4                     Howard Portnoy   
5                    Daniel Nussbaum   
6                    Alissa J. Rubin   
7       Megan Twohey and Scott Shane   
8                        Aaron Klein   
9                    Chris Tomlinson   
10                     Amando Flavio   
11                        Jason Ditz   
12                      AnotherAnnie   
13                     Jack Williams   
14  Michael Corkery and Stacy Cowley   
15                          Starkman   
16                           The Doc   
17                         Jeff Poor   
18                     Jerome Hudson   
19                           Pam Key   

                                                 text  label  
0   House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1   Ever get the feeling your life circles the rou...      0  
2   Why the Truth Might Get You Fired October 29, ...      1  
3   Videos 15 Civilians Killed In Single US Airstr...      1  
4   Print \nAn Iranian woman has been sentenced to...      1  
5   In these trying times, Jackie Mason is the Voi...      0  
6   PARIS  —   France chose an idealistic, traditi...      0  
7   A week before Michael T. Flynn resigned as nat...      0  
8   Organizing for Action, the activist group that...      0  
9   The BBC produced spoof on the “Real Housewives...      0  
10  The mystery surrounding The Third Reich and Na...      1  
11  Clinton Campaign Demands FBI Affirm Trump's Ru...      1  
12  Yes, There Are Paid Government Trolls On Socia...      1  
13  Guillermo Barros Schelotto was not the first A...      0  
14  The scandal engulfing Wells Fargo toppled its ...      0  
15  A Caddo Nation tribal leader has just been fre...      1  
16  FBI Closes In On Hillary! Posted on Home » Hea...      1  
17  Wednesday after   Donald Trump’s press confere...      0  
18  Screenwriter Ryan Murphy, who has produced the...      0  
19  Sunday on MSNBC’s “AM Joy,” actor and director...      0

In [12]:
x = df.drop('label',axis = 1)


In [13]:
y = df['label']

In [14]:
x.shape

(18285, 4)

In [15]:
y.shape

(18285,)

In [16]:
import tensorflow as tf
tf.__version__

'2.10.0'

In [17]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [18]:
voc_size = 5000

In [19]:
messages = x.copy()
messages['title'][6]

'Benoît Hamon Wins French Socialist Party’s Presidential Nomination - The New York Times'

In [20]:
len(messages)

18285

In [21]:
import nltk
import re
from nltk.corpus import stopwords

In [23]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [24]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [25]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [26]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [27]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [28]:
onehot_repr = [one_hot(words,voc_size) for words in corpus]
onehot_repr

[[1292, 47, 2914, 4088, 3892, 171, 4938, 175, 1012, 1136],
 [4530, 2110, 1230, 641, 1852, 1471, 3761],
 [2212, 2310, 2606, 1159],
 [1301, 1264, 4679, 2944, 570, 1978],
 [1300, 1852, 977, 4902, 4574, 3565, 1852, 3267, 2877, 3272],
 [3201,
  2708,
  3457,
  4132,
  4374,
  1167,
  1089,
  4157,
  3681,
  1866,
  3485,
  920,
  1346,
  279,
  3761],
 [2686, 1815, 4447, 2414, 3722, 598, 1013, 2464, 295, 1175, 2235],
 [2986, 605, 4939, 3880, 481, 4357, 1167, 733, 295, 1175, 2235],
 [4481, 2748, 1155, 824, 1961, 3821, 30, 323, 1167, 868],
 [2452, 2300, 3594, 2713, 3926, 1299, 3513, 2879],
 [1736, 3252, 1831, 2525, 1887, 4096, 679, 4908, 3692, 1424, 3183],
 [2944, 1571, 3892, 3821, 1167, 481],
 [2462, 4752, 1602, 1852, 3353, 2115, 1775, 1475, 4285],
 [2430, 1093, 4924, 4422, 3338, 2005, 1372, 295, 1175, 2235],
 [704, 4672, 2938, 4943, 3122, 295, 1175, 2235],
 [906, 2934, 3452, 1098, 2476, 2446, 4791, 556, 1338, 354],
 [2738, 1069, 2110],
 [2347, 3989, 4074, 4129, 1167, 674, 500, 3761],
 [4985

In [29]:
onehot_repr[1]

[4530, 2110, 1230, 641, 1852, 1471, 3761]

In [30]:
sent_length = 20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[1292   47 2914 ...    0    0    0]
 [4530 2110 1230 ...    0    0    0]
 [2212 2310 2606 ...    0    0    0]
 ...
 [ 538 3881 4553 ...    0    0    0]
 [4471  481   97 ...    0    0    0]
 [4740 2413 1752 ...    0    0    0]]


In [31]:
## Creating model
embedding_vector_features=40 ##features representation

#A Sequential model is appropriate for a plain stack of layers where each layer has exactly one
#input tensor and one output tensor.
model=Sequential()

# Embedding layer enables us to convert each word into a fixed length vector of defined size
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))

In [32]:

model.add(LSTM(100))

In [33]:
#Dense layer is the regular deeply connected neural network layer.
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [34]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)
X_final.shape,y_final.shape
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [35]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 10s 36ms/step - loss: 0.3154 - accuracy: 0.8488 - val_loss: 0.2043 - val_accuracy: 0.9162
Epoch 2/10
192/192 [==============================] - 5s 28ms/step - loss: 0.1295 - accuracy: 0.9515 - val_loss: 0.2267 - val_accuracy: 0.9064
Epoch 3/10
192/192 [==============================] - 5s 27ms/step - loss: 0.0786 - accuracy: 0.9738 - val_loss: 0.3051 - val_accuracy: 0.8976
Epoch 4/10
192/192 [==============================] - 5s 27ms/step - loss: 0.0508 - accuracy: 0.9835 - val_loss: 0.2859 - val_accuracy: 0.9075
Epoch 5/10
192/192 [==============================] - 5s 29ms/step - loss: 0.0364 - accuracy: 0.9887 - val_loss: 0.2919 - val_accuracy: 0.9099
Epoch 6/10
192/192 [==============================] - 5s 28ms/step - loss: 0.0239 - accuracy: 0.9931 - val_loss: 0.3501 - val_accuracy: 0.9046
Epoch 7/10
192/192 [==============================] - 5s 28ms/step - loss: 0.0228 - accuracy: 0.9924 - val_loss: 0.4062 - val_accuracy: 0.907

In [36]:
from sklearn.metrics import confusion_matrix


y_pred=model.predict(X_test)


y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

confusion_matrix(y_test,y_pred)

189/189 [==============================] - 2s 7ms/step


array([[3098,  321],
       [ 254, 2362]], dtype=int64)

In [37]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9047224523612262

In [38]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.91      0.92      3419
           1       0.88      0.90      0.89      2616

    accuracy                           0.90      6035
   macro avg       0.90      0.90      0.90      6035
weighted avg       0.91      0.90      0.90      6035

